### ISSUE TITLE
Kullanıcı Kaydı

### ISSUE THREAD

**Issue by enkob** [Kodluyoruz/discord-register-bot#2]
Discord sunucusunun yeni bir kullanıcısı olarak, özel içeriğe erişebilmek ve topluluğa katılabilmek için hesabımı sunucuya kaydettirebilmek istiyorum.

Discord Kayıt odasına ilk katıldığımda karşıma komutunu yazdığımda, bot, kullanıcıya verilen kayıt kodunu girmem için bir ekran gösterir.

Kullanıcı Kodumu girdikten sonra bot, Kodun geçerli olduğunu kontrol etmelidir.

Kullanıcının Kodu geçerliyse, bot beni sunucuya kayıtlı bir kullanıcı olarak eklemelidir

Kullanıcı başarılı bir şekilde kaydolduktan sonra, bot kayıt bilgilerine veya tercihlerine dayanarak otomatik olarak roller atayabilmelidir.

Kullanıcı Kodu geçersizse, bot, default üye olarak kayıt etmeli.

"Tebrikler" ekranı ile işlemi bitirilmeli.

**Comment by enkob** [comment]
![Image](https://user-images.githubusercontent.com/130500728/234669246-d06517ee-b99e-419d-a66c-f8648b2bfd7a.png)
![Image](https://user-images.githubusercontent.com/130500728/234669244-08b3e5fc-34c3-4ffd-8870-b89287ce843d.png)
![Image](https://user-images.githubusercontent.com/130500728/234669245-e8558a72-5f3c-45dc-89b7-98c3266c369f.png)

**Comment by azateser** [comment]
İlk Aşamada Olacaklar için Tüm Tasarım: https://www.figma.com/file/qNPjC3RgbF5iyFTZQzHVjS/Discord-Register-Bot-UX-(KODLUYORUZ-AKK)?node-id=64%3A1577&t=aQcjyClQ9mZrgyyt-1

Kullanıcı Kayıt Ekranı İçin: https://www.figma.com/file/qNPjC3RgbF5iyFTZQzHVjS/Discord-Register-Bot-UX-(KODLUYORUZ-AKK)?node-id=64%3A2270&t=aQcjyClQ9mZrgyyt-1



![Image](https://user-images.githubusercontent.com/16418661/234705725-e03cabc6-86d6-4377-bfc3-fe985a1c2598.png)



![Image](https://user-images.githubusercontent.com/16418661/234705734-23ed9dbe-29cf-4645-a969-286c6af93381.png)



![Image](https://user-images.githubusercontent.com/16418661/234705739-c9efa544-0e0a-4172-8889-1cdf04a32f43.png)

**Comment by azateser** [comment]
Yönetici - Kayıt Oluştur'a taşındı comment
